version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    # Uncomment below lines for live-reload during development
    # volumes:
    #   - ./app:/app/app
    # command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"